ALTER TABLE user_devices
  ADD COLUMN device_name VARCHAR(100) DEFAULT NULL AFTER device_id,
  ADD COLUMN province VARCHAR(32) DEFAULT NULL,
  ADD COLUMN city VARCHAR(32) DEFAULT NULL,
  ADD COLUMN district VARCHAR(32) DEFAULT NULL,
  ADD COLUMN customer_type VARCHAR(16) DEFAULT 'individual',
  ADD COLUMN industry VARCHAR(32) DEFAULT NULL;
